### ISSUE TITLE
TRACKING: Private FS Work

### ISSUE THREAD

**Issue by appcypher** [wnfs-wg/rs-wnfs#14]
Implement WNFSv2 private filesystem. This will be one of the initial work to get WNFSv2 private filesystem working.
Here are some of the things that should be implemented:

- [x] HAMT for file tree storage (https://github.com/WebNativeFileSystem/rs-wnfs/issues/24)
- [x] Bloom/name filter with ancestry check support (https://github.com/WebNativeFileSystem/rs-wnfs/issues/26)
- [x] Skip ratchet for backward secrecy and forward transparency (https://github.com/WebNativeFileSystem/rs-skip-ratchet/issues/1)
- [x] IPLD serialization (https://github.com/WebNativeFileSystem/rs-wnfs/issues/29)
- [x] Private filesystem APIs (Rust and WebAssembly) (https://github.com/WebNativeFileSystem/rs-wnfs/issues/30)
- [x] Encrypt Header Inside the Private Node (https://github.com/wnfs-wg/rs-wnfs/issues/47)
- [x] Implement Seeking & Seeking + Recovering Reads - (https://github.com/wnfs-wg/rs-wnfs/issues/46)
- [x] Implement `mv` (https://github.com/wnfs-wg/rs-wnfs/issues/54)
