### ISSUE TITLE
Fission/Banyan roadmap

### ISSUE THREAD

**Issue by bdehaynin** [wnfs-wg/rs-wnfs#266]
**Goal:** Identify all dependencies between Fission and Banyan projects, prioritize them, and set them up over a timeline based on common objectives.

_All lists in this issue are non-exhaustive_

Resources:
- [Banyan onboarding architecture](https://www.figma.com/file/i7uQgAKgrpHw5sGTecwPwh/our-onboarding-architecture?type=whiteboard&t=YouDhnw9mREaRJW5-0)
- [WNFS Working Group](https://github.com/wnfs-wg)
  - [WNFS roadmap](https://github.com/orgs/wnfs-wg/projects/1) 
- [UCAN working group](https://github.com/ucan-wg)
- www.banyan.computer / www.tombolo.store

### Preliminary Questions
- What dependencies do Fission and Banyan have? On which projects?
  - ODD SDK → Tombolo
    - WNFS
    - UCAN
  - Iroh 
- Banyan roadmap?

### Tasks to breakdown and prioritize
Boxes for quick reorder:
- [ ] Backwards compatibility - **2 months goal (Mid July-ish)**
- [ ] Blockstores
- [ ] Philipp: Symlinks? Deduplication?
- [ ] Philipp: Compression?
- [ ] Philipp: Content-Defined Chunking?
- [ ] Philipp: Directory Sharding?
- [ ] Volumes?
- [ ] Mutability

### Visual Roadmap
[Figma](https://www.figma.com/file/DR9G4Jx7ksqs5Hci0sDpPS/Untitled?type=whiteboard&node-id=0%3A1&t=pBF3aVOc1JLbhJJS-1)

### Documentation to write
On Fission side: 
On Banyan side:
