### ISSUE TITLE
Tracking: State & rough Roadmap

### ISSUE THREAD

**Issue by matheus23** [wnfs-wg/rs-wnfs#81]
## What exists in `rs-wnfs` today

Public File System:
- [x] `read`, `write`, `mkdir`, `ls`, `mv`, `rm`, of public files/directories
- [x] history for public files and directories
- [x] arbitrary metadata for files and directories
- [x] data structure in place for enabling 

Private File System:
- [x] `read`, `write`, `mkdir`, `ls`, `mv`, `rm`, `cp`, private files/directories with a ~262kb limit on private file size & ~2500 directory entry limit on private directories
- [x] key derivation from a skip ratchet, i.e. being able to share only future versions without sharing past
- [x] history for private files and directories
- [x] arbitrary metadata for files and directories

## Upcoming

Public File System:
- [ ] Diffing of two file systems for write verification
- [ ] Merge algorithm implementation for conflict resolution

Private File System:
- [ ] data structure in place enabling conflict resolution #74 #56 
- [ ] private file sharding #80
- [ ] switch from GCAs/"nyberg accumulators"/bloomfilters to RSA Accumulators for unlimited history tree depth, enabling DAG structures, improving security margin
- [ ] shared private files
- [ ] private directory sharding (not high priority right now)

For both:
- [ ] Symlinking across file systems (enabling shared private files)

**Comment by ehsan6sha** [comment]
can you please elaborate on "shared private files"? I know it was briefly mentioned over the call but didn't we say sharing is irrelevant to WNFS and will be done through UCANs? 
Is it the "sharing in" and "sharing out" thing so that WNFS handles the sharing instead of the developer having to manage it separately? And what is the priority for it?

**Comment by matheus23** [comment]
@ehsan6sha we want to support end-user flows that look like this: https://guide.fission.codes/developers/webnative/sharing-private-data

> Is it the "sharing in" and "sharing out" thing so that WNFS handles the sharing instead of the developer having to manage it separately?

Yes. `rs-wnfs` itself is a fairly low-level library. A JS/TS developer would use APIs similar to the one from the link above.
`rs-wnfs` would handle the creation of payloads for sharing private data and utilities for consuming them, allowing you to retrieve `PrivateRef`s for looking up nodes in the private forest.

> And what is the priority for it?

Fairly high, but not immediately the next thing we're working on:
Step 1 for us is getting the private file system ready, so the data structure is set up to support algorithms like conflict resolution.
Step 2 is going to be shared private file support.

**Comment by matheus23** [comment]
Closing this in favor of the public roadmap: https://github.com/orgs/wnfs-wg/projects/1/views/1
